/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhaRouteImport } from './routes/pha'
import { Route as GerarRouteImport } from './routes/gerar'
import { Route as CutterRouteImport } from './routes/cutter'
import { Route as IndexRouteImport } from './routes/index'

const PhaRoute = PhaRouteImport.update({
  id: '/pha',
  path: '/pha',
  getParentRoute: () => rootRouteImport,
} as any)
const GerarRoute = GerarRouteImport.update({
  id: '/gerar',
  path: '/gerar',
  getParentRoute: () => rootRouteImport,
} as any)
const CutterRoute = CutterRouteImport.update({
  id: '/cutter',
  path: '/cutter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cutter': typeof CutterRoute
  '/gerar': typeof GerarRoute
  '/pha': typeof PhaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cutter': typeof CutterRoute
  '/gerar': typeof GerarRoute
  '/pha': typeof PhaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cutter': typeof CutterRoute
  '/gerar': typeof GerarRoute
  '/pha': typeof PhaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cutter' | '/gerar' | '/pha'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cutter' | '/gerar' | '/pha'
  id: '__root__' | '/' | '/cutter' | '/gerar' | '/pha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CutterRoute: typeof CutterRoute
  GerarRoute: typeof GerarRoute
  PhaRoute: typeof PhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pha': {
      id: '/pha'
      path: '/pha'
      fullPath: '/pha'
      preLoaderRoute: typeof PhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerar': {
      id: '/gerar'
      path: '/gerar'
      fullPath: '/gerar'
      preLoaderRoute: typeof GerarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cutter': {
      id: '/cutter'
      path: '/cutter'
      fullPath: '/cutter'
      preLoaderRoute: typeof CutterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CutterRoute: CutterRoute,
  GerarRoute: GerarRoute,
  PhaRoute: PhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
